# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
  - job: 'windows_test'
    pool:
      vmImage: windows-latest
    steps:
      - task: PowerShell@2
        displayName: "Run pester tests"
        inputs:
          targetType: 'inline'
          script: |
            Install-Module -Scope CurrentUser -Force -AllowClobber -SkipPublisherCheck Pester;
            Import-Module Pester;
            $configuration = [PesterConfiguration]::Default;
            $configuration.CodeCoverage.Enabled = $true;
            $configuration.CodeCoverage.Path = (Get-ChildItem src/*.ps1 | ForEach-Object{$_.FullName});
            $configuration.CodeCoverage.OutputFormat = "JaCoCo";
            $configuration.TestResult.Enabled = $true;
            $configuration.Run.Exit = $true;
            $configuration.Run.Path = (Get-ChildItem tests/*ps1 | ForEach-Object{$_.FullName});
            Invoke-Pester -Configuration $configuration;
          showWarnings: true
          pwsh: true
      - task: PublishTestResults@2
        condition: always()
        inputs:
          testResultsFormat: 'NUnit'
          testResultsFiles: 'testResults.xml'
          failTaskOnFailedTests: true
          testRunTitle: 'CZ.PowerShell.NetworkTools'
      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
            PathtoPublish: 'coverage.xml'
            ArtifactName: 'windows-coverage'
            publishLocation: Container
  - job: 'linux_test'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: PowerShell@2
        displayName: "Run pester tests"
        inputs:
          targetType: 'inline'
          script: |
            Install-Module -Scope CurrentUser -Force -AllowClobber -SkipPublisherCheck Pester;
            Import-Module Pester;
            $configuration = [PesterConfiguration]::Default;
            $configuration.CodeCoverage.Enabled = $true;
            $configuration.CodeCoverage.Path = (Get-ChildItem src/*.ps1 | ForEach-Object{$_.FullName});
            $configuration.CodeCoverage.OutputFormat = "JaCoCo";
            $configuration.TestResult.Enabled = $true;
            $configuration.Run.Exit = $true;
            $configuration.Run.Path = (Get-ChildItem tests/*ps1 | ForEach-Object{$_.FullName});
            Invoke-Pester -Configuration $configuration;
          showWarnings: true
          pwsh: true
      - task: PublishTestResults@2
        condition: always()
        inputs:
          testResultsFormat: 'NUnit'
          testResultsFiles: 'testResults.xml'
          failTaskOnFailedTests: true
          testRunTitle: 'CZ.PowerShell.NetworkTools'
      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
            PathtoPublish: 'coverage.xml'
            ArtifactName: 'linux-coverage'
            publishLocation: Container
  - job: 'build_package'
    pool:
      vmImage: windows-latest
    dependsOn:
      - 'windows_test'
      - 'linux_test'
    steps:
      - task: PowerShell@2
        displayName: "Build the powershell package"
        inputs:
          filePath: 'build/build.ps1'
          showWarnings: true
          pwsh: true
      - task: PublishBuildArtifacts@1
        inputs:
            PathtoPublish: 'src/bin/'
            ArtifactName: 'drop'
            publishLocation: 'Container'
  - job: 'publish_coverage'
    pool:
      vmImage: windows-latest
    dependsOn:
      - 'windows_test'
      - 'linux_test'
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download Coverage Windows Artifacts'
        inputs:
          artifactName: windows-coverage
          downloadPath: $(System.DefaultWorkingDirectory)/
      - task: DownloadBuildArtifacts@0
        displayName: 'Download Coverage Linux Artifacts'
        inputs:
          artifactName: linux-coverage
          downloadPath: $(System.DefaultWorkingDirectory)/
      - task: PublishCodeCoverageResults@1
        condition: always()
        inputs:
          codeCoverageTool: 'JaCoCo'
          summaryFileLocation: 'windows-coverage/coverage.xml'
          additionalCodeCoverageFiles: 'linux-coverage/coverage.xml'
          pathToSources: 'src/'
          failIfCoverageEmpty: true